-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mw_window\mw_window_dut.vhd
-- Created: 2020-12-24 09:34:25
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mw_window_dut
-- Source Path: mw_window/mw_window_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mw_window_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        Length                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Address                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Enable                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        Valid_Real_In                     :   IN    std_logic;  -- ufix1
        Data_Real_In                      :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        Last_Real_In                      :   IN    std_logic;  -- ufix1
        User_Real_In                      :   IN    std_logic;  -- ufix1
        Valid_Imag_In                     :   IN    std_logic;  -- ufix1
        Data_Imag_In                      :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        Last_Imag_In                      :   IN    std_logic;  -- ufix1
        User_Imag_In                      :   IN    std_logic;  -- ufix1
        rd_s2m_rd_aready                  :   IN    std_logic;  -- ufix1
        rd_s2m_rd_dvalid                  :   IN    std_logic;  -- ufix1
        rd_data                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        ce_out                            :   OUT   std_logic;  -- ufix1
        dma_ready                         :   OUT   std_logic;  -- ufix1
        Valid_Real_Out                    :   OUT   std_logic;  -- ufix1
        Data_Real_Out                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        Last_Real_Out                     :   OUT   std_logic;  -- ufix1
        User_Real_Out                     :   OUT   std_logic;  -- ufix1
        Valid_Imag_Out                    :   OUT   std_logic;  -- ufix1
        Data_Imag_Out                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        Last_Imag_Out                     :   OUT   std_logic;  -- ufix1
        User_Imag_Out                     :   OUT   std_logic;  -- ufix1
        rd_m2s_rd_addr                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        rd_m2s_rd_len                     :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        rd_m2s_rd_avalid                  :   OUT   std_logic  -- ufix1
        );
END mw_window_dut;


ARCHITECTURE rtl OF mw_window_dut IS

  -- Component Declarations
  COMPONENT mw_window_src_mw_window
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          Length                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Address                         :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Enable                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          Valid_Real_In                   :   IN    std_logic;  -- ufix1
          Data_Real_In                    :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Last_Real_In                    :   IN    std_logic;  -- ufix1
          User_Real_In                    :   IN    std_logic;  -- ufix1
          Valid_Imag_In                   :   IN    std_logic;  -- ufix1
          Data_Imag_In                    :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          Last_Imag_In                    :   IN    std_logic;  -- ufix1
          User_Imag_In                    :   IN    std_logic;  -- ufix1
          rd_s2m_rd_aready                :   IN    std_logic;  -- ufix1
          rd_s2m_rd_dvalid                :   IN    std_logic;  -- ufix1
          rd_data                         :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          ce_out                          :   OUT   std_logic;  -- ufix1
          dma_ready                       :   OUT   std_logic;  -- ufix1
          Valid_Real_Out                  :   OUT   std_logic;  -- ufix1
          Data_Real_Out                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          Last_Real_Out                   :   OUT   std_logic;  -- ufix1
          User_Real_Out                   :   OUT   std_logic;  -- ufix1
          Valid_Imag_Out                  :   OUT   std_logic;  -- ufix1
          Data_Imag_Out                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          Last_Imag_Out                   :   OUT   std_logic;  -- ufix1
          User_Imag_Out                   :   OUT   std_logic;  -- ufix1
          rd_m2s_rd_addr                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          rd_m2s_rd_len                   :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          rd_m2s_rd_avalid                :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : mw_window_src_mw_window
    USE ENTITY work.mw_window_src_mw_window(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Valid_Real_In_sig                : std_logic;  -- ufix1
  SIGNAL Last_Real_In_sig                 : std_logic;  -- ufix1
  SIGNAL User_Real_In_sig                 : std_logic;  -- ufix1
  SIGNAL Valid_Imag_In_sig                : std_logic;  -- ufix1
  SIGNAL Last_Imag_In_sig                 : std_logic;  -- ufix1
  SIGNAL User_Imag_In_sig                 : std_logic;  -- ufix1
  SIGNAL rd_s2m_rd_aready_sig             : std_logic;  -- ufix1
  SIGNAL rd_s2m_rd_dvalid_sig             : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL dma_ready_sig                    : std_logic;  -- ufix1
  SIGNAL Valid_Real_Out_sig               : std_logic;  -- ufix1
  SIGNAL Data_Real_Out_sig                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Last_Real_Out_sig                : std_logic;  -- ufix1
  SIGNAL User_Real_Out_sig                : std_logic;  -- ufix1
  SIGNAL Valid_Imag_Out_sig               : std_logic;  -- ufix1
  SIGNAL Data_Imag_Out_sig                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Last_Imag_Out_sig                : std_logic;  -- ufix1
  SIGNAL User_Imag_Out_sig                : std_logic;  -- ufix1
  SIGNAL rd_m2s_rd_addr_sig               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL rd_m2s_rd_len_sig                : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL rd_m2s_rd_avalid_sig             : std_logic;  -- ufix1

BEGIN
  u_mw_window_src_mw_window : mw_window_src_mw_window
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              Length => Length,  -- ufix32
              Address => Address,  -- ufix32
              Enable => Enable,  -- ufix32
              Valid_Real_In => Valid_Real_In_sig,  -- ufix1
              Data_Real_In => Data_Real_In,  -- ufix16
              Last_Real_In => Last_Real_In_sig,  -- ufix1
              User_Real_In => User_Real_In_sig,  -- ufix1
              Valid_Imag_In => Valid_Imag_In_sig,  -- ufix1
              Data_Imag_In => Data_Imag_In,  -- ufix16
              Last_Imag_In => Last_Imag_In_sig,  -- ufix1
              User_Imag_In => User_Imag_In_sig,  -- ufix1
              rd_s2m_rd_aready => rd_s2m_rd_aready_sig,  -- ufix1
              rd_s2m_rd_dvalid => rd_s2m_rd_dvalid_sig,  -- ufix1
              rd_data => rd_data,  -- ufix16
              ce_out => ce_out_sig,  -- ufix1
              dma_ready => dma_ready_sig,  -- ufix1
              Valid_Real_Out => Valid_Real_Out_sig,  -- ufix1
              Data_Real_Out => Data_Real_Out_sig,  -- ufix16
              Last_Real_Out => Last_Real_Out_sig,  -- ufix1
              User_Real_Out => User_Real_Out_sig,  -- ufix1
              Valid_Imag_Out => Valid_Imag_Out_sig,  -- ufix1
              Data_Imag_Out => Data_Imag_Out_sig,  -- ufix16
              Last_Imag_Out => Last_Imag_Out_sig,  -- ufix1
              User_Imag_Out => User_Imag_Out_sig,  -- ufix1
              rd_m2s_rd_addr => rd_m2s_rd_addr_sig,  -- ufix32
              rd_m2s_rd_len => rd_m2s_rd_len_sig,  -- ufix16
              rd_m2s_rd_avalid => rd_m2s_rd_avalid_sig  -- ufix1
              );

  Valid_Real_In_sig <= Valid_Real_In;

  Last_Real_In_sig <= Last_Real_In;

  User_Real_In_sig <= User_Real_In;

  Valid_Imag_In_sig <= Valid_Imag_In;

  Last_Imag_In_sig <= Last_Imag_In;

  User_Imag_In_sig <= User_Imag_In;

  rd_s2m_rd_aready_sig <= rd_s2m_rd_aready;

  rd_s2m_rd_dvalid_sig <= rd_s2m_rd_dvalid;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  dma_ready <= dma_ready_sig;

  Valid_Real_Out <= Valid_Real_Out_sig;

  Data_Real_Out <= Data_Real_Out_sig;

  Last_Real_Out <= Last_Real_Out_sig;

  User_Real_Out <= User_Real_Out_sig;

  Valid_Imag_Out <= Valid_Imag_Out_sig;

  Data_Imag_Out <= Data_Imag_Out_sig;

  Last_Imag_Out <= Last_Imag_Out_sig;

  User_Imag_Out <= User_Imag_Out_sig;

  rd_m2s_rd_addr <= rd_m2s_rd_addr_sig;

  rd_m2s_rd_len <= rd_m2s_rd_len_sig;

  rd_m2s_rd_avalid <= rd_m2s_rd_avalid_sig;

END rtl;

