-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mw_ssrconverter\mw_ssrconverter_src_SSR1_to_SSR8.vhd
-- Created: 2020-12-22 10:57:15
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mw_ssrconverter_src_SSR1_to_SSR8
-- Source Path: mw_ssrconverter/SSR Subset Converter/SSR Serializer Imag/SSR1 to SSR8
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.mw_ssrconverter_src_SSR_Subset_Converter_pkg.ALL;

ENTITY mw_ssrconverter_src_SSR1_to_SSR8 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Data_In                           :   IN    vector_of_std_logic_vector16(0 TO 7);  -- uint16 [8]
        Index                             :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        Data_Out                          :   OUT   vector_of_std_logic_vector16(0 TO 7);  -- uint16 [8]
        Valid_Out                         :   OUT   std_logic
        );
END mw_ssrconverter_src_SSR1_to_SSR8;


ARCHITECTURE rtl OF mw_ssrconverter_src_SSR1_to_SSR8 IS

  -- Signals
  SIGNAL Index_unsigned                   : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Data_In_0                        : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous7_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant1_out1        : std_logic;
  SIGNAL Data_In_0_1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous6_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant2_out1        : std_logic;
  SIGNAL Data_In_0_2                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous5_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant3_out1        : std_logic;
  SIGNAL Data_In_0_3                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous4_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant4_out1        : std_logic;
  SIGNAL Data_In_0_4                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous3_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL Data_In_0_5                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous2_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant6_out1        : std_logic;
  SIGNAL Data_In_0_6                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous1_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant7_out1        : std_logic;
  SIGNAL Data_In_0_7                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Unit_Delay_Enabled_Synchronous_out1 : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Vector_Concatenate_out1          : vector_of_unsigned16(0 TO 7);  -- uint16 [8]
  SIGNAL Unit_Delay_out1                  : std_logic;

BEGIN
  Index_unsigned <= unsigned(Index);

  
  Compare_To_Constant_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#0#, 3) ELSE
      '0';

  Data_In_0 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous7_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous7_out1 <= Data_In_0;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous7_process;


  
  Compare_To_Constant1_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#1#, 3) ELSE
      '0';

  Data_In_0_1 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous6_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant1_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous6_out1 <= Data_In_0_1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous6_process;


  
  Compare_To_Constant2_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#2#, 3) ELSE
      '0';

  Data_In_0_2 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous5_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant2_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous5_out1 <= Data_In_0_2;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous5_process;


  
  Compare_To_Constant3_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#3#, 3) ELSE
      '0';

  Data_In_0_3 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous4_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant3_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous4_out1 <= Data_In_0_3;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous4_process;


  
  Compare_To_Constant4_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#4#, 3) ELSE
      '0';

  Data_In_0_4 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous3_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant4_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous3_out1 <= Data_In_0_4;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous3_process;


  
  Compare_To_Constant5_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#5#, 3) ELSE
      '0';

  Data_In_0_5 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous2_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant5_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous2_out1 <= Data_In_0_5;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous2_process;


  
  Compare_To_Constant6_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#6#, 3) ELSE
      '0';

  Data_In_0_6 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous1_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant6_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous1_out1 <= Data_In_0_6;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous1_process;


  
  Compare_To_Constant7_out1 <= '1' WHEN Index_unsigned = to_unsigned(16#7#, 3) ELSE
      '0';

  Data_In_0_7 <= unsigned(Data_In(0));

  Unit_Delay_Enabled_Synchronous_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Synchronous_out1 <= to_unsigned(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND Compare_To_Constant7_out1 = '1' THEN
        Unit_Delay_Enabled_Synchronous_out1 <= Data_In_0_7;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Synchronous_process;


  Vector_Concatenate_out1(0) <= Unit_Delay_Enabled_Synchronous7_out1;
  Vector_Concatenate_out1(1) <= Unit_Delay_Enabled_Synchronous6_out1;
  Vector_Concatenate_out1(2) <= Unit_Delay_Enabled_Synchronous5_out1;
  Vector_Concatenate_out1(3) <= Unit_Delay_Enabled_Synchronous4_out1;
  Vector_Concatenate_out1(4) <= Unit_Delay_Enabled_Synchronous3_out1;
  Vector_Concatenate_out1(5) <= Unit_Delay_Enabled_Synchronous2_out1;
  Vector_Concatenate_out1(6) <= Unit_Delay_Enabled_Synchronous1_out1;
  Vector_Concatenate_out1(7) <= Unit_Delay_Enabled_Synchronous_out1;

  outputgen: FOR k IN 0 TO 7 GENERATE
    Data_Out(k) <= std_logic_vector(Vector_Concatenate_out1(k));
  END GENERATE;

  Unit_Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_out1 <= Compare_To_Constant7_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay_process;


  Valid_Out <= Unit_Delay_out1;

END rtl;

