-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mw_spectrumanalyser\mw_spectrumanalyser_src_nfp_wire_single_block.vhd
-- Created: 2020-12-23 14:04:00
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mw_spectrumanalyser_src_nfp_wire_single_block
-- Source Path: mw_spectrumanalyser/Spectrum Analyser/Spectrum Options/nfp_wire_single
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mw_spectrumanalyser_src_nfp_wire_single_block IS
  PORT( nfp_in                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        nfp_out                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END mw_spectrumanalyser_src_nfp_wire_single_block;


ARCHITECTURE rtl OF mw_spectrumanalyser_src_nfp_wire_single_block IS

BEGIN
  nfp_out <= nfp_in;

END rtl;

