-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\spectrum_analyser\SpectrumAnalyser_src_Rising_Edge_Detector_block.vhd
-- Created: 2021-01-21 21:23:19
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SpectrumAnalyser_src_Rising_Edge_Detector_block
-- Source Path: spectrum_analyser/Spectrum Analyser/Spectrum Analyser/Spectrum Analyser Core/SSR Subset Converter/SSR 
-- Serializer Imag/SSR2 to SSR8/Rising Edge Detecto
-- Hierarchy Level: 6
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SpectrumAnalyser_src_Rising_Edge_Detector_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_16_0                        :   IN    std_logic;
        In1                               :   IN    std_logic;
        Out1                              :   OUT   std_logic
        );
END SpectrumAnalyser_src_Rising_Edge_Detector_block;


ARCHITECTURE rtl OF SpectrumAnalyser_src_Rising_Edge_Detector_block IS

  -- Signals
  SIGNAL NOT_out1                         : std_logic;
  SIGNAL Delay_out1                       : std_logic;
  SIGNAL AND1_out1                        : std_logic;

BEGIN
  NOT_out1 <=  NOT In1;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_16_0 = '1' THEN
        Delay_out1 <= NOT_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  AND1_out1 <= Delay_out1 AND In1;

  Out1 <= AND1_out1;

END rtl;

