-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mw_autodma\mw_autodma_src_mw_autodma.vhd
-- Created: 2020-12-24 09:17:12
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.90625e-09
-- Target subsystem base rate: 3.90625e-09
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.90625e-09
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Buffer_Pointer                ce_out        3.90625e-09
-- DMA_Status                    ce_out        3.90625e-09
-- wr_m2s_wr_addr                ce_out        3.90625e-09
-- wr_m2s_wr_len                 ce_out        3.90625e-09
-- wr_m2s_wr_valid               ce_out        3.90625e-09
-- wr_data                       ce_out        3.90625e-09
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mw_autodma_src_mw_autodma
-- Source Path: mw_autodma/mw_autodma
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mw_autodma_src_mw_autodma IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Length                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Buffer_Address_1                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Buffer_Address_2                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Buffer_Address_3                  :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Enable                            :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        Count                             :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_tvalid                     :   IN    std_logic;
        s_axis_tdata                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        s_axis_tuser                      :   IN    std_logic;
        s_axis_tlast                      :   IN    std_logic;
        wr_s2m_wr_ready                   :   IN    std_logic;
        wr_s2m_wr_complete                :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Buffer_Pointer                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        DMA_Status                        :   OUT   std_logic_vector(5 DOWNTO 0);  -- ufix6
        wr_m2s_wr_addr                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        wr_m2s_wr_len                     :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        wr_m2s_wr_valid                   :   OUT   std_logic;
        wr_data                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END mw_autodma_src_mw_autodma;


ARCHITECTURE rtl OF mw_autodma_src_mw_autodma IS

  -- Component Declarations
  COMPONENT mw_autodma_src_Direct_Memory_Access
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Length                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Count                           :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Buffer_Address_1                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Buffer_Address_2                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Buffer_Address_3                :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Enable_DMA                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Valid_In                        :   IN    std_logic;
          Data_In                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Start_In                        :   IN    std_logic;
          wr_ready_wr_ready               :   IN    std_logic;
          wr_ready_wr_complete            :   IN    std_logic;
          wr_data                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          wr_m2s_wr_addr                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          wr_m2s_wr_len                   :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
          wr_m2s_wr_valid                 :   OUT   std_logic;
          Buffer_Pointer                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          DMA_Status                      :   OUT   std_logic_vector(5 DOWNTO 0)  -- ufix6
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : mw_autodma_src_Direct_Memory_Access
    USE ENTITY work.mw_autodma_src_Direct_Memory_Access(rtl);

  -- Signals
  SIGNAL Direct_Memory_Access_out1        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Direct_Memory_Access_out2_wr_addr : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Direct_Memory_Access_out2_wr_len : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Direct_Memory_Access_out2_wr_valid : std_logic;
  SIGNAL buffer_rsvd                      : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL y                                : std_logic_vector(5 DOWNTO 0);  -- ufix6

BEGIN
  u_Direct_Memory_Access : mw_autodma_src_Direct_Memory_Access
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Length => Length,  -- uint32
              Count => Count,  -- uint32
              Buffer_Address_1 => Buffer_Address_1,  -- uint32
              Buffer_Address_2 => Buffer_Address_2,  -- uint32
              Buffer_Address_3 => Buffer_Address_3,  -- uint32
              Enable_DMA => Enable,  -- uint32
              Valid_In => s_axis_tvalid,
              Data_In => s_axis_tdata,  -- uint32
              Start_In => s_axis_tuser,
              wr_ready_wr_ready => wr_s2m_wr_ready,
              wr_ready_wr_complete => wr_s2m_wr_complete,
              wr_data => Direct_Memory_Access_out1,  -- uint32
              wr_m2s_wr_addr => Direct_Memory_Access_out2_wr_addr,  -- uint32
              wr_m2s_wr_len => Direct_Memory_Access_out2_wr_len,  -- uint32
              wr_m2s_wr_valid => Direct_Memory_Access_out2_wr_valid,
              Buffer_Pointer => buffer_rsvd,  -- ufix2
              DMA_Status => y  -- ufix6
              );

  ce_out <= clk_enable;

  Buffer_Pointer <= buffer_rsvd;

  DMA_Status <= y;

  wr_m2s_wr_addr <= Direct_Memory_Access_out2_wr_addr;

  wr_m2s_wr_len <= Direct_Memory_Access_out2_wr_len;

  wr_m2s_wr_valid <= Direct_Memory_Access_out2_wr_valid;

  wr_data <= Direct_Memory_Access_out1;

END rtl;

