-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mw_autodma\mw_autodma_axi4_master_rd.vhd
-- Created: 2020-12-16 17:10:11
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: mw_autodma_axi4_master_rd
-- Source Path: mw_autodma/mw_autodma_axi4_master_rd
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY mw_autodma_axi4_master_rd IS
  PORT( AXI4_Master_Rd_RDATA              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Master_Rd_RLAST              :   IN    std_logic;  -- ufix1
        AXI4_Master_Rd_RVALID             :   IN    std_logic;  -- ufix1
        AXI4_Master_Rd_RID                :   IN    std_logic;  -- ufix1
        AXI4_Master_Rd_RRESP              :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Master_Rd_ARREADY            :   IN    std_logic;  -- ufix1
        AXI4_Master_Rd_ARID               :   OUT   std_logic;  -- ufix1
        AXI4_Master_Rd_ARADDR             :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Master_Rd_ARLEN              :   OUT   std_logic_vector(7 DOWNTO 0);  -- ufix8
        AXI4_Master_Rd_ARSIZE             :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        AXI4_Master_Rd_ARBURST            :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI4_Master_Rd_ARLOCK             :   OUT   std_logic;  -- ufix1
        AXI4_Master_Rd_ARCACHE            :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI4_Master_Rd_ARPROT             :   OUT   std_logic_vector(2 DOWNTO 0);  -- ufix3
        AXI4_Master_Rd_ARVALID            :   OUT   std_logic;  -- ufix1
        AXI4_Master_Rd_RREADY             :   OUT   std_logic  -- ufix1
        );
END mw_autodma_axi4_master_rd;


ARCHITECTURE rtl OF mw_autodma_axi4_master_rd IS

  -- Signals
  SIGNAL const_0_1                        : std_logic;  -- ufix1
  SIGNAL const_araddr                     : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_arlen                      : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL const_arsize                     : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL const_1_2                        : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL const_3_4                        : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL const_0_3                        : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL const_1_1                        : std_logic;  -- ufix1

BEGIN
  const_0_1 <= '0';

  const_araddr <= to_unsigned(0, 32);

  AXI4_Master_Rd_ARADDR <= std_logic_vector(const_araddr);

  const_arlen <= to_unsigned(16#00#, 8);

  AXI4_Master_Rd_ARLEN <= std_logic_vector(const_arlen);

  const_arsize <= to_unsigned(16#2#, 3);

  AXI4_Master_Rd_ARSIZE <= std_logic_vector(const_arsize);

  const_1_2 <= to_unsigned(16#1#, 2);

  AXI4_Master_Rd_ARBURST <= std_logic_vector(const_1_2);

  const_3_4 <= to_unsigned(16#3#, 4);

  AXI4_Master_Rd_ARCACHE <= std_logic_vector(const_3_4);

  const_0_3 <= to_unsigned(16#0#, 3);

  AXI4_Master_Rd_ARPROT <= std_logic_vector(const_0_3);

  const_1_1 <= '1';

  AXI4_Master_Rd_ARID <= const_0_1;

  AXI4_Master_Rd_ARLOCK <= const_0_1;

  AXI4_Master_Rd_ARVALID <= const_0_1;

  AXI4_Master_Rd_RREADY <= const_1_1;

END rtl;

